---
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Restart SSH
  systemd:
    name: sshd
    state: restarted

- name: Reboot System
  reboot:
    msg: "Rebooting.."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Logout KDE Session
  shell: qdbus-qt6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout || true
  args:
    executable: /bin/bash
  become: no
