- name: dnf copr enable crashdummy/Displaylink
  command:
    cmd: dnf copr enable -y crashdummy/Displaylink

- name: Update packages after copr enable
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install displaylink driver
  dnf:
    name: displaylink
    state: present
