- name: Ensure SSH directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0700'

- name: Check if GitHub SSH key exists
  stat:
    path: "{{ ansible_env.HOME }}/.ssh/github"
  register: github_sshkey

- name: Check if public server ssh key exists
  stat:
    path: "{{ ansible_env.HOME }}/.ssh/public_server"
  register: public_server_sshkey

- name: Generate SSH key for GitHub if it doesn't exist
  command: ssh-keygen -t ed25519 -f "{{ ansible_env.HOME }}/.ssh/github" -C "christopherjmacgregor@gmail.com" -N "{{ github_ssh_password }}"
  become_user: "{{ ansible_user }}"
  when: not github_sshkey.stat.exists

- name: Generate SSH key for public servers if it doesn't exist
  command: ssh-keygen -t ed25519 -f "{{ ansible_env.HOME }}/.ssh/public_server" -C "christopherjmacgregor@gmail.com" -N "{{ public_server_ssh_password }}"
  become_user: "{{ ansible_user }}"
  when: not public_server_sshkey.stat.exists

# keys are managed via keychain and auto start via bashrc

- name: Remind where keys are
  vars:
    msg: |
      SSH keys generated in ~/.ssh
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
