---
- name: Remove default user directories
  become: true
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - "Documents"
    - "Videos"
    - "Pictures"
    - "Music"
    - "Public"
    - "Templates"

- name: Copy custom rc files
  become: true
  copy:
    src: "files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  loop:
    - ".bashrc"
    - ".bash_aliases"
    - ".tmux.conf"
    - ".tmux.conf.local"
    - ".tmux-pane-border.sh"
    - ".gitconfig"
