- name: Copy plasmashellrc
  copy:
    src: files/plasmashellrc
    dest: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone McMojave-kde repository
  git:
    repo: https://github.com/vinceliuice/McMojave-kde.git
    dest: "{{ ansible_env.HOME }}/McMojave-kde"
    update: yes
    version: master
  become_user: "{{ ansible_user }}"

- name: Run McMojave-kde install script
  shell: ./install.sh
  args:
    chdir: "{{ ansible_user_dir }}/McMojave-kde"
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Clone WhiteSur-icon-theme repository
  git:
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    dest: "{{ ansible_env.HOME }}/WhiteSur-icon-theme"
    update: yes
    version: master
  become_user: "{{ ansible_user }}"

- name: Run WhiteSur-icon-theme install script
  shell: ./install.sh -t default
  args:
    chdir: "{{ ansible_env.HOME }}/WhiteSur-icon-theme"
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  loop:
    - src: files/plasmashellrc
      dest: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    - src: files/plasma-org.kde.plasma.desktop-appletsrc
      dest: "{{ ansible_env.HOME }}/.config/plasma-org.kde.plasma.desktop-appletsrc"

# TODO
  #- name: Cleanup installed git repos
