- name: Copy plasmashellrc
  copy:
    src: files/plasmashellrc
    dest: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone McMojave-kde repository
  git:
    repo: https://github.com/vinceliuice/McMojave-kde.git
    dest: "{{ ansible_env.HOME }}/McMojave-kde"
    update: yes
    version: master
  become_user: "{{ ansible_user }}"

- name: Run McMojave-kde install script
  shell: ./install.sh
  args:
    chdir: "{{ ansible_user_dir }}/McMojave-kde"
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Clone WhiteSur-icon-theme repository
  git:
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    dest: "{{ ansible_env.HOME }}/WhiteSur-icon-theme"
    update: yes
    version: master
  become_user: "{{ ansible_user }}"

- name: Run WhiteSur-icon-theme install script
  shell: ./install.sh -t default
  args:
    chdir: "{{ ansible_env.HOME }}/WhiteSur-icon-theme"
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  loop:
    - src: files/plasmashellrc
      dest: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    - src: files/plasma-org.kde.plasma.desktop-appletsrc
      dest: "{{ ansible_env.HOME }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    - src: files/defaults
      dest: "{{ ansible_env.HOME }}/.local/share/plasma/look-and-feel/com.github.vinceliuice.McMojave/contents/defaults"

- name: Apply lookandfeel McMojave
  shell: |
    lookandfeeltool -a com.github.vinceliuice.McMojave
    timeout 5 kquitapp5 plasmashell
    pgrep -U $USER -x plasmashell &>/dev/null && pkill -U $USER -x plasmashell
    pgrep -U $USER -x plasmashell &>/dev/null && pkill -U $USER -x -9 plasmashell
    pgrep -U $USER -x plasmashell &>/dev/null && echo "ERROR: cannot kill plasmashell"
    plasmashell &
  become_user: "{{ ansible_user }}"

- name: Cleanup installed git repos
    file:
      path: "{{ item }}"
      state: absent
    become: no
    become_user: "{{ ansible_user }}"
    loop:
      - "{{ ansible_env.HOME }}/McMojave-kde"
      - "{{ ansible_env.HOME }}/WhiteSur-icon-theme"
