---
# tasks that need 'sudo'
- block:
  - import_tasks: packages.yml
  - import_tasks: security.yml
  - import_tasks: github-sshgen.yml
  #  - include_tasks: keyboard-binding.yml
  - import_tasks: displaylink-driver.yml
  - import_tasks: nvidia-driver.yml
  become: yes

# tasks without sudo
- block:
  - import_tasks: macos_theme.yml
  - import_tasks: homedir.yml
  become: no
