---
# tasks that need 'sudo'
- block:
  - import_tasks: packages.yml
  - import_tasks: security.yml
  - import_tasks: gen_sshkeys.yml
  - import_tasks: displaylink_driver.yml
  - import_tasks: nvidia_driver.yml
  become: yes

# tasks without sudo
- block:
  - import_tasks: kde_theme.yml
  - import_tasks: homedir.yml
  become: no
