---
# Update and upgrade system packages
- name: Update and upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes

# help prompt

# remove initial bloat
- name: Remove non-essential packages
  become: true
  package:
    name:
      - "@LibreOffice"
      - libreoffice*
      - akregator 
      - ark
      - akonadi-contacts
      - plasma-discover
      - elisa-player
      - dragon
      - plasma-drkonqi
      - emoji*
      - mediawriter
      - filelight
      - firewall-config
      - gwenview
      - gnome-abrt
      - im-chooser
      - khelpcenter
      - kinfocenter
      - kamoso
      - kcharselect
      - kde-connect
      - kde-partitionmanager
      - kfind
      - kmahjongg
      - kmines
      - kmousetool
      - kmouth
      - kolourpaint
      - kpat
      - krfb
      - kvantum
      - kwalletmanager5
      - kwrite
      - neochat
      - okular
      - skanpage
      - spectacle
      - plasma-systemmonitor
      - plasma-welcome
    autoremove: yes
    state: absent

# Install basic utilities
- name: Install basic utilities
  dnf:
    name:
      - xclip
      - tmux
      - zoxide
      - neovim
      - keychain
      - gnome-boxes
      - cmake
      - make
      - g++
      - gcc
      - docker
    state: present
