---
# Update and upgrade system packages
- name: Update and upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  notify: Reboot System

# remove initial bloat
- name: Remove non-essential packages
  become: true
  package:
    name:
#      - ImageMagick
#      - ImageMagick-libs
#      - LibRaw
#      - ffmpeg-free
#      - ffmpegthumbs
#      - vlc-libs
#      - freeglut
#      - NetworkManager-l2tp
#      - NetworkManager-libreswan
#      - NetworkManager-openconnect
#      - NetworkManager-openvpn
#      - NetworkManager-pptp
#      - NetworkManager-vpnc
#      - openvpn
#      - aajohan-comfortaa-fonts
#      - abattis-cantarell-fonts
#      - jomolhari-fonts
#      - anaconda
#      - anaconda-core
#      - anaconda-gui
#      - anaconda-install-env-deps
#      - anaconda-live
#      - anaconda-tui
#      - anaconda-widgets
#      - initial-setup
#      - initial-setup-gui
#      - initial-setup-gui-wayland-plasma
#      - abrt
#      - abrt-addon-ccpp
#      - abrt-addon-kerneloops
#      - abrt-addon-pstoreoops
#      - abrt-addon-vmcore
#      - abrt-addon-xorg
#      - abrt-cli
#      - abrt-dbus
#      - abrt-desktop
#      - abrt-gui
#      - abrt-gui-libs
#      - abrt-plugin-bodhi
#      - abrt-tui
#      - gnome-abrt
#      - cups
#      - cups-browsed
#      - cups-filters
#      - cups-filters-driverless
#      - cups-ipptool
#      - cups-pk-helper
#      - braille-printer-app
#      - bluez-cups
#      - akonadi-calendar
#      - akonadi-contacts
#      - akonadi-import-wizard
#      - akonadi-mime
#      - akonadi-notes
#      - akonadi-search
#      - akonadi-server
#      - akonadi-server-mysql
#      - akregator
#      - akregator-libs
#      - ark
#      - ark-libs
#      - audiocd-kio
#      - audiocd-kio-doc
#      - dragon
#      - elisa-player
#      - filelight
#      - kamoso
#      - kgpg
#      - khelpcenter
#      - kimageannotator-common
#      - kimageannotator-qt6
#      - kio-gdrive
#      - kmahjongg
#      - kmail
#      - kmail-account-wizard
#      - kmail-libs
#      - kmailtransport
#      - kmines
#      - kolourpaint
#      - kolourpaint-libs
#      - kontact
#      - korganizer
#      - korganizer-libs
#      - kpat
#      - krdc
#      - krfb
#      - ksshaskpass
#      - ktnef
#      - kwalletmanager5
#      - kwrite
#      - plasma-discover
#      - plasma-discover-flatpak
#      - plasma-discover-libs
#      - plasma-discover-notifier
#      - plasma-discover-offline-updates
#      - plasma-discover-packagekit
#      - plasma-vault
#      - spectacle
#      - flatpak-kcm
#      - ibus-anthy
#      - ibus-anthy-python
#      - ibus-hangul
#      - ibus-libpinyin
#      - ibus-libzhuyin
#      - ibus-m17n
#      - ibus-typing-booster
#      - kasumi-common
#      - kasumi-unicode
#      - b43-fwcutter
#      - b43-openfwwf
#      - hfsplus-tools
#      - hfsutils
#      - jfsutils
#      - jq
#      - man-db
#      - man-pages
#      - pinfo
#      - antiword
#      - deltarpm
#      - lsof
#      - nano
#      - orca
#      - spice-vdagent
#      - xorg-x11-xauth
#      - avahi-gobject
#      - SDL_image
#      - freecell-solver-data
    state: absent

# Install basic utilities
- name: Install basic utilities
  dnf:
    name:
      - xclip
      - tmux
      - zoxide
      - neovim
      - keychain
      - cmake
      - make
      - g++
      - gcc
      - kvantum
      - qt5-qttools
      - nautilus
      - sassc
    state: present
