---
# Update and upgrade system packages
- name: Update and upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  notify: Reboot System

# remove initial bloat
- name: Remove non-essential packages
  become: true
  package:
    name:
      - NetworkManager.x86_64
      - NetworkManager-libnm.x86_64
      - acl.x86_64
      - alternatives.x86_64
      - attr.x86_64
      - audit.x86_64
      - audit-libs.x86_64
      - audit-rules.x86_64
      - authselect.x86_64
      - authselect-libs.x86_64
      - basesystem.noarch
      - bash.x86_64
      - btrfs-progs.x86_64
      - bzip2.x86_64
      - bzip2-libs.x86_64
      - ca-certificates.noarch
      - checkpolicy.x86_64
      - chrony.x86_64
      - coreutils.x86_64
      - coreutils-common.x86_64
      - cracklib.x86_64
      - cracklib-dicts.x86_64
      - cronie.x86_64
      - cronie-anacron.x86_64
      - crontabs.noarch
      - crypto-policies.noarch
      - crypto-policies-scripts.noarch
      - cryptsetup.x86_64
      - cryptsetup-libs.x86_64
      - curl.x86_64
      - cyrus-sasl-lib.x86_64
      - dbus.x86_64
      - dbus-broker.x86_64
      - dbus-common.noarch
      - dbus-daemon.x86_64
      - dbus-libs.x86_64
      - deltarpm.x86_64
      - device-mapper.x86_64
      - device-mapper-event.x86_64
      - device-mapper-event-libs.x86_64
      - device-mapper-libs.x86_64
      - device-mapper-persistent-data.x86_64
      - dhcp-client.x86_64
      - dhcp-common.noarch
      - distribution-gpg-keys.noarch
      - dnf.noarch
      - dnf-data.noarch
      - dnf-plugins-core.noarch
      - dracut.x86_64
      - e2fsprogs.x86_64
      - e2fsprogs-libs.x86_64
      - efibootmgr.x86_64
      - efivar-libs.x86_64
      - elfutils.x86_64
      - elfutils-libelf.x86_64
      - elfutils-libs.x86_64
      - ethtool.x86_64
      - expat.x86_64
      - fedora-release-common.noarch
      - fedora-repos.noarch
      - file.x86_64
      - file-libs.x86_64
      - filesystem.x86_64
      - findutils.x86_64
      - firewalld.noarch
      - firewalld-filesystem.noarch
      - fontconfig.x86_64
      - freetype.x86_64
      - fuse.x86_64
      - fuse-libs.x86_64
      - fuse3.x86_64
      - fuse3-libs.x86_64
      - gawk.x86_64
      - gdbm.x86_64
      - gdbm-libs.x86_64
      - glib2.x86_64
      - glibc.x86_64
      - glibc-common.x86_64
      - grub2-common.noarch
      - grub2-efi-ia32.x86_64
      - grub2-efi-x64.x86_64
      - grub2-pc.x86_64
      - grub2-tools.x86_64
      - grub2-tools-minimal.x86_64
      - grubby.x86_64
      - gzip.x86_64
      - hostname.x86_64
      - iproute.x86_64
      - iputils.x86_64
      - kernel.x86_64
      - kernel-core.x86_64
      - kernel-modules.x86_64
      - konsole.x86_64
      - less.x86_64
      - libgcc.x86_64
      - libgcrypt.x86_64
      - libgpg-error.x86_64
      - libmount.x86_64
      - libselinux.x86_64
      - libselinux-utils.x86_64
      - libsemanage.x86_64
      - libsepol.x86_64
      - libstdc++.x86_64
      - libuuid.x86_64
      - libzstd.x86_64
      - lvm2.x86_64
      - lvm2-libs.x86_64
      - ncurses-base.noarch
      - ncurses-libs.x86_64
      - openssh.x86_64
      - openssh-clients.x86_64
      - openssh-server.x86_64
      - openssl-libs.x86_64
      - pam.x86_64
      - pcre.x86_64
      - pcre2.x86_64
      - perl-interpreter.x86_64
      - plasma-desktop.x86_64
      - policycoreutils.x86_64
      - polkit.x86_64
      - popt.x86_64
      - procps-ng.x86_64
      - python3.x86_64
      - readline.x86_64
      - rpm.x86_64
      - rpm-libs.x86_64
      - sed.x86_64
      - selinux-policy.noarch
      - selinux-policy-targeted.noarch
      - setup.noarch
      - shadow-utils.x86_64
      - shim-ia32.x86_64
      - shim-x64.x86_64
      - sudo.x86_64
      - systemd.x86_64
      - systemd-libs.x86_64
      - systemd-pam.x86_64
      - systemd-udev.x86_64
      - tar.x86_64
      - tzdata.noarch
      - util-linux.x86_64
      - vim-minimal.x86_64
      - xz.x86_64
      - xz-libs.x86_64
      - yum.noarch
    state: absent

# Install basic utilities
- name: Install basic utilities
  dnf:
    name:
      - xclip
      - tmux
      - zoxide
      - neovim
      - cmake
      - make
      - g++
      - gcc
      - kvantum
      - qt5-qttools
      - nautilus
      - sassc
    state: present
