---
# Update and upgrade system packages
- name: Update and upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes

# remove initial bloat
- name: Remove non-essential packages
  become: true
  package:
    name:
      - libreoffice*
      - rhythmbox
      - cheese
      - gnome-music
      - tracker
      - tracker-miners
      - gnome-sudoku
      - gnome-mines
      - gnome-mahjongg
      - gnome-weather
      - gnome-maps
      - gnome-photos
      - simple-scan
      - thermald
      - toolbox
      - thrift
      - zfs-fuse
      - tesseract
      - tesseract-langpack-eng
      - texlive-lib
      - zig-srpm-macros
      - zeromq
    state: absent

# Install basic utilities
- name: Install basic utilities
  dnf:
    name:
      - htop
      - xclip
      - tmux
      - zoxide
    state: present
