---
# Update and upgrade system packages
- name: Update and upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  notify: Reboot System

# remove initial bloat
- name: Remove non-essential packages
  become: true
  package:
    name:
      - Box2D.x86_64
      - ImageMagick.x86_64
      - ImageMagick-libs.x86_64
      - LibRaw.x86_64
      - NetworkManager-l2tp.x86_64
      - NetworkManager-libreswan.x86_64
      - NetworkManager-openconnect.x86_64
      - NetworkManager-openvpn.x86_64
      - NetworkManager-pptp.x86_64
      - NetworkManager-vpnc.x86_64
      - SDL2.x86_64
      - SDL_image.x86_64
      - aajohan-comfortaa-fonts.noarch
      - abattis-cantarell-fonts.noarch
      - abattis-cantarell-vf-fonts.noarch
      - abrt.x86_64
      - abrt-addon-ccpp.x86_64
      - abrt-addon-kerneloops.x86_64
      - abrt-addon-pstoreoops.x86_64
      - abrt-addon-vmcore.x86_64
      - abrt-addon-xorg.x86_64
      - abrt-cli.x86_64
      - abrt-dbus.x86_64
      - abrt-desktop.x86_64
      - abrt-gui.x86_64
      - abrt-gui-libs.x86_64
      - abrt-plugin-bodhi.x86_64
      - abrt-tui.noarch
      - adobe-mappings-cmap.noarch
      - adobe-mappings-cmap-deprecated.noarch
      - adobe-mappings-pdf.noarch
      - adobe-source-code-pro-fonts.noarch
      - aha.x86_64
      - akonadi-calendar.x86_64
      - akonadi-contacts.x86_64
      - akonadi-import-wizard.x86_64
      - akonadi-mime.x86_64
      - akonadi-notes.x86_64
      - akonadi-search.x86_64
      - akonadi-server.x86_64
      - akonadi-server-mysql.x86_64
      - akregator.x86_64
      - akregator-libs.x86_64
      - anaconda.x86_64
      - anaconda-core.x86_64
      - anaconda-gui.x86_64
      - anaconda-install-env-deps.x86_64
      - anaconda-live.noarch
      - anaconda-tui.x86_64
      - anaconda-widgets.x86_64
      - ansible.noarch
      - ansible-core.noarch
      - antiword.x86_64
      - ark.x86_64
      - ark-libs.x86_64
      - aspell.x86_64
      - aspell-en.x86_64
      - at.x86_64
      - audiocd-kio.x86_64
      - audiocd-kio-doc.noarch
      - autocorr-en.noarch
      - avahi.x86_64
      - avahi-glib.x86_64
      - avahi-gobject.x86_64
      - baloo-widgets.x86_64
      - b43-fwcutter.x86_64
      - b43-openfwwf.noarch
      - bluez-cups.x86_64
      - braille-printer-app.x86_64
      - cryfs.x86_64
      - cups.x86_64
      - cups-browsed.x86_64
      - cups-filters.x86_64
      - cups-filters-driverless.x86_64
      - cups-ipptool.x86_64
      - cups-pk-helper.x86_64
      - cyrus-sasl-md5.x86_64
      - cyrus-sasl-plain.x86_64
      - deltarpm.x86_64
      - desktop-backgrounds-compat.noarch
      - dolphin-plugins.x86_64
      - dragon.x86_64
      - elisa-player.x86_64
      - ffmpeg-free.x86_64
      - ffmpegthumbs.x86_64
      - filelight.x86_64
      - flatpak.x86_64
      - flatpak-kcm.x86_64
      - flashrom.x86_64
      - freecell-solver-data.noarch
      - freeglut.x86_64
      - geoclue2.x86_64
      - gnome-abrt.x86_64
      - grantlee-editor.x86_64
      - grantlee-editor-libs.x86_64
      - grantleetheme.x86_64
      - gwenview.x86_64
      - gwenview-libs.x86_64
      - hfsplus-tools.x86_64
      - hfsutils.x86_64
      - ibus-anthy.x86_64
      - ibus-anthy-python.noarch
      - ibus-hangul.x86_64
      - ibus-libpinyin.x86_64
      - ibus-libzhuyin.x86_64
      - ibus-m17n.x86_64
      - ibus-typing-booster.noarch
      - initial-setup.x86_64
      - initial-setup-gui.x86_64
      - initial-setup-gui-wayland-plasma.noarch
      - jfsutils.x86_64
      - jomolhari-fonts.noarch
      - jq.x86_64
      - kamoso.x86_64
      - kasumi-common.noarch
      - kasumi-unicode.x86_64
      - kde-inotify-survey.x86_64
      - kde-partitionmanager.x86_64
      - kdegraphics-mobipocket.x86_64
      - kdegraphics-thumbnailers.x86_64
      - kdepim-addons.x86_64
      - kdepim-runtime.x86_64
      - kdepim-runtime-libs.x86_64
      - kdeplasma-addons.x86_64
      - kgpg.x86_64
      - khelpcenter.x86_64
      - kimageannotator-common.x86_64
      - kimageannotator-qt6.x86_64
      - kio-gdrive.x86_64
      - kmahjongg.x86_64
      - kmail.x86_64
      - kmail-account-wizard.x86_64
      - kmail-libs.x86_64
      - kmailtransport.x86_64
      - kmines.x86_64
      - kolourpaint.x86_64
      - kolourpaint-libs.x86_64
      - kontact.x86_64
      - korganizer.x86_64
      - korganizer-libs.x86_64
      - kpat.x86_64
      - krdc.x86_64
      - krfb.x86_64
      - ksshaskpass.x86_64
      - ksystemstats.x86_64
      - ktnef.x86_64
      - kwalletmanager5.x86_64
      - kwrite.x86_64
      - kwrited.x86_64
      - lsof.x86_64
      - man-db.x86_64
      - man-pages.noarch
      - mpage.x86_64
      - nano.x86_64
      - okular.x86_64
      - okular-libs.x86_64
      - okular-part.x86_64
      - orca.noarch
      - pinfo.x86_64
      - plasma-discover.x86_64
      - plasma-discover-flatpak.x86_64
      - plasma-discover-libs.x86_64
      - plasma-discover-notifier.x86_64
      - plasma-discover-offline-updates.x86_64
      - plasma-discover-packagekit.x86_64
      - plasma-vault.x86_64
      - spectacle.x86_64
      - spice-vdagent.x86_64
      - vlc-libs.x86_64
      - xorg-x11-xauth.x86_64
    state: absent

# Install basic utilities
- name: Install basic utilities
  dnf:
    name:
      - xclip
      - tmux
      - zoxide
      - neovim
      - cmake
      - make
      - g++
      - gcc
      - kvantum
      - qt5-qttools
      - nautilus
      - sassc
    state: present
